apiVersion: apps/v1
kind: Deployment
metadata:
  name: starwars-api
spec:
  selector:
    matchLabels:
      app: starwars-api
  replicas: 3 # Rodar 3 replicas
  template:
    metadata:
      labels:
        app: starwars-api
    spec:
      containers:
      - name: starwars-api
        image: eversonpereira/starwars-api:0.0.1
        ports:
        - containerPort: 9000